### ISSUE TITLE
technitium helm chart not working with argocd

### ISSUE THREAD

**Issue by rserbitar** [obeone/charts#16]
when doing

`argocd app create technitium --file technitium.yaml`

I get

`FATA[0000] rpc error: code = InvalidArgument desc = application spec for technitium is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template technitium --namespace technitium --kube-version 1.32 --values <path to cached source>/apps/technitium/technitium-values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: technitium-dnsserver/templates/NOTES.txt:1:4: executing "technitium-dnsserver/templates/NOTES.txt" at <include "common.notes.defaultNotes" .>: error calling include: template: technitium-dnsserver/charts/common/templates/_notes.tpl:33:16: executing "common.notes.defaultNotes" at <first .paths>: error calling first: runtime error: invalid memory address or nil pointer dereference%0A%0AUse --debug flag to render out invalid YAML`

Unfortunately I am not that good with authoring my own helm charts. But the `technitium-dnsserver/templates/NOTES.txt` looks kind of strange.

Cheers,

serbitar

**Comment by obeone** [comment]
Hi,

I (Ok... a LLM :p) rewrote `NOTES.txt`. Can you confirm that with the last version (1.5.5) of the chart, it's now ok ?

The problem did not seem to be specific to ArgoCD but rather to an installation without ingress.

**Comment by rserbitar** [comment]
I am installing with ingress.

I check now without argocd to exclude that, and only with helm.

My values file is:

```
ingress:
  main:
    enabled: true
    hosts:
      - host: xxx
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          xxx
        secretName: technitium_certificate_secret

persistence:
  config:
    enabled: true
    type: pvc
    size: 500Mi
```

The error I get now (both with helm and argocd):

`Error: template: technitium-dnsserver/templates/NOTES.txt:2:18: executing "technitium-dnsserver/templates/NOTES.txt" at <include "common.names.namespace" .>: error calling include: template: no template "common.names.namespace" associated with template "gotpl"`
